### ISSUE TITLE
Allow usage of `restart` instead of `softRestart`

### ISSUE THREAD

**Issue by kaero** [nodules/luster-guard#1]
As for now, master restart workers using `Master#softRestart()`. It can take a lot of time for some apps, so we can add an option to extension config to allow the master to use `Master#restart()` *(hard restart)* for restarting workers on FS events.

**Comment by narqo** [comment]
:+1: Using soft restart doesn't look necessary for development needs.

**Comment by kaero** [comment]
\cc @Flackus

**Comment by Flackus** [comment]
:+1: to @narqo
