### ISSUE TITLE
Decomposition of the luster-guard

### ISSUE THREAD

**Issue by Aetet** [nodules/luster-guard#5]
Hello. Separate luster-guard on two modules:
1. watcher, which monitors files and emit events about filesystem stuff
2. worker-restarter, which restarts worker processes when appropriate filesystem events happened.

This separation helps to write new modules and increase modularity.

**Comment by kaero** [comment]
Suggested decomposition looks useless now: any extension can restart workers in the way it likes without introduction of some sort of "fs events", which hard to unify due to differences of filesystems & platforms.
